### ISSUE TITLE
TypeError: 'BlastAlignment' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-api#12]
I get the following error from hommod in hope. The input to HOPE is:

```
MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPRMPEAAPPVAPAPAAPTPAAPAPAPSWPLSSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLRKKGEPHHELPPGSTKRALPNNTSSSPQPKKKPLDGEYFTLQIRGRERFEMFRELNEALELKDAQAGKEPGGSRAHSSHLKSKKGQSTSRHKKLMFKTEGPDSD
```

The mutation is `E349R`.

```
ServiceError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 33, in create_model
    paths = modeler.modelProc (sequence, species_id, residue_number, False)
  File "/usr/src/app/hommod_rest/services/model.py", line 815, in modelProc
    domainalign.getAlignments (ranges, mainTargetSeq)
  File "/usr/src/app/hommod_rest/services/domainalign.py", line 734, in getAlignments
    alignment, pid, pcover)
  File "/usr/src/app/hommod_rest/services/domainalign.py", line 560, in _get_range_from
    m = getCoveredTargetRange(alignment)
  File "/usr/src/app/hommod_rest/services/domainalign.py", line 435, in getCoveredTargetRange
    while not alignment['target'][targetStart].isalpha():
TypeError: 'BlastAlignment' object has no attribute '__getitem__'
```

**Comment by cbaakman** [comment]
This commit should fix it:
https://github.com/cmbi/hommod-rest/commit/f6e8f6c64d57933765f8fd9da9d9d6fa055f13e8
