### ISSUE TITLE
Exception: No template blast hit syntax

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-api#13]
I got the following error from hommod when using HOPE.

```
ServiceError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 33, in create_model
    paths = modeler.modelProc (sequence, species_id, residue_number, False)
  File "/usr/src/app/hommod_rest/services/model.py", line 815, in modelProc
    domainalign.getAlignments (ranges, mainTargetSeq)
  File "/usr/src/app/hommod_rest/services/domainalign.py", line 701, in getAlignments
    pdbid, pdbchain = getTemplatePDBIDandChain(hitID)
  File "/usr/src/app/hommod_rest/services/modelutils.py", line 329, in getTemplatePDBIDandChain
    raise Exception("No template blast hit syntax: \'%s\'" % blastHitID)
Exception: No template blast hit syntax: 'pdb|4KZZ|g'
```

**Comment by cbaakman** [comment]
This commit should fix it:
https://github.com/cmbi/hommod-rest/commit/f98da4e5fc00876601b08ef5fa195ef607482804
