### ISSUE TITLE
Exception: alignment not provided for interacting chain B

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-api#14]
Another error from hommod when using HOPE:

```
Exception: the following models have failed:
6dd7080c-8fdb-6b4d-993d-75bfe3060c94_HUMAN_13-1488:
Traceback (most recent call last):
  File "/usr/src/app/hommod_rest/services/model.py", line 927, in modelProc
    mainTargetSeq, mainDomainRange)
  File "/usr/src/app/hommod_rest/services/model.py", line 636, in _build_for_domain
    yasaraChains, interactingChainAlignments)
  File "/usr/src/app/hommod_rest/services/interaction.py", line 98, in __init__
    "interacting chain %s" % chainID)
Exception: alignment not provided for interacting chain B
```

**Comment by cbaakman** [comment]
This commit should fix it:
https://github.com/cmbi/hommod-rest/commit/3bd8433075f9dab0be68b55d719ef06fb39fb3c2
