### ISSUE TITLE
Exception: main domain range: 33 - 732 exceeds sequence length(721)

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-api#59]
I get this error in HOPE. What does it mean? Can anything be done about it?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 60, in create_model
    template_id)
  File "/usr/src/app/hommod_rest/services/model.py", line 1014, in modelProc
    raise Exception("the following models have failed:\n" + s)
Exception: the following models have failed:
147b60cf-e161-6093-2b7f-390a5b952991_HUMAN_34-732_3LY6-A:
Traceback (most recent call last):
  File "/usr/src/app/hommod_rest/services/model.py", line 944, in modelProc
    main_target_sequence, main_domain_range)
  File "/usr/src/app/hommod_rest/services/model.py", line 432, in _build_for_domain
    len(main_target_sequence)))
Exception: main domain range: 33 - 732 exceeds sequence length(721)
```

**Comment by cbaakman** [comment]
Input sequence is MGQGEPSQRSTGLAGLYAAPAASPVFIKGSGMDALGIKSCDFQAARNNEEHHTKALSSRRLFVRRGQPFTIILYFRAPVRAFLPALKKVALTAQTGEQPSKINRTQATFPISSLGDRKWWSAVVEERDAQSWTISVTTPADAVIGHYSLLLQVSGRKQLLLGQFTLLFNPWNREDAVFLKNEAQRMEYLLNQNGLIYLGTADCIQAESWDFGQFEGDVIDLSLRLLSKDKQVEKWSQPVHVARVLGALLHFLKEQRVLPTPQTQATQEGALLNKRRGSVPILRQWLTGRGRPVYDGQAWVLAAVACTVLRCLGIPARVVTTFASAQGTGGRLLIDEYYNEEGLQNGEGQRGRIWIFQTSTECWMTRPALPQGYDGWQILHPSAPNGGGVLGSCDLVPVRAVKEGTLGLTPAVSDLFAAINASCVVWKCCEDGTLELTDSNTKYVGNNISTKGVGSDRCEDITQNYKYPEGSLQEKEVLERVEKEKMEREKDNGIRPPSLETASPLYLLLKAPSSLPLRGDAQISVTLVNHSEQEKAVQLAIGVQAVHYNGVLAAKLWRKKLHLTLSANLEKIITIGLFFSNFERNPPENTFLRLTAMATHSESNLSCFAQEDIAICRPHLAIKMPEKAEQYQPLTASVSLQNSLDAPMEDCVISILGRGLIHRERSYRFRSVWPENTMCAKFQFTPTHVGLQRLTVEVDCNMFQNLTNYKSVTVVAPELSA correct?

I'll look into it!

**Comment by jonblack** [comment]
I have another instance of this bug so I think your fix isn't complete. Can you take another look, please?

```
Model job failed:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 60, in create_model
    template_id)
  File "/usr/src/app/hommod_rest/services/model.py", line 1014, in modelProc
    raise Exception("the following models have failed:\n" + s)
Exception: the following models have failed:
219431be-dd08-494f-e25a-a71ab19af72d_HUMAN_1610-1832_2YPD-A:
Traceback (most recent call last):
  File "/usr/src/app/hommod_rest/services/model.py", line 944, in modelProc
    main_target_sequence, main_domain_range)
  File "/usr/src/app/hommod_rest/services/model.py", line 432, in _build_for_domain
    len(main_target_sequence)))
Exception: main domain range: 1609 - 1832 exceeds sequence length(1761)
```
