### ISSUE TITLE
Exception: inteproscan job timed out

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-api#61]
I get the following error in HOPE from hommod.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 60, in create_model
    template_id)
  File "/usr/src/app/hommod_rest/services/model.py", line 786, in modelProc
    ranges = interpro.get_domain_locations(main_target_sequence)
  File "/usr/src/app/hommod_rest/services/interpro.py", line 181, in get_domain_locations
    filepath = self._create_data_file(sequence)
  File "/usr/src/app/hommod_rest/services/interpro.py", line 164, in _create_data_file
    raise Exception("inteproscan job timed out")
Exception: inteproscan job timed out
```

How long is the timeout and can we do anything to prevent this causing issue in HOPE?

**Comment by cbaakman** [comment]
timeout is set here https://github.com/cmbi/hommod-api/blob/master/hommod_rest/services/interpro.py#L154
It's 1000 seconds.

Without an interpro file, hommod cannot continue.

**Comment by jonblack** [comment]
Can you increase the timeout to 1800 seconds (30 minutes). We'll see if that improves it.

**Comment by jonblack** [comment]
I'm still seeing this error in HOPE. Can you increase the timeout to 3600 seconds (one hour), please?

**Comment by cbaakman** [comment]
OK, done it.

**Comment by jonblack** [comment]
Commit?

**Comment by cbaakman** [comment]
Over here: https://github.com/cmbi/hommod-api/commit/09df7f8c44d17a658e2ace893c7bb73795605a7b
