### ISSUE TITLE
Mismatch between alignment and template sequence

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-api#67]
The following error appeared in HOPE:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 60, in create_model
    template_id)
  File "/usr/src/app/hommod_rest/services/model.py", line 1014, in modelProc
    raise Exception("the following models have failed:\n" + s)
Exception: the following models have failed:
9a6424c4-4096-d62d-4150-e38ebec3799b_HUMAN_32-188_3UX9-A:
Traceback (most recent call last):
  File "/usr/src/app/hommod_rest/services/model.py", line 944, in modelProc
    main_target_sequence, main_domain_range)
  File "/usr/src/app/hommod_rest/services/model.py", line 628, in _build_for_domain
    targetsInterproRanges, picker)
  File "/usr/src/app/hommod_rest/services/domainalign.py", line 439, in pickAlignments
    if picker.accepts(targetID, alignment):
  File "/usr/src/app/hommod_rest/services/interaction.py", line 80, in accepts
    sstart, send = get_target_covered_range(subjectChainAlignment, sseq)
  File "/usr/src/app/hommod_rest/services/modelutils.py", line 812, in get_target_covered_range
    % (alignment['template'], template_seq))
Exception: mismatch between alignment and template sequence:
IVLTQPPSVSGAPGQRVTISCSGSSSNIGSNYVSWYQQLPGTAPKLLIYDNNQRPSGVPDRFSGSKSGTSASLAITGLQSEDEADYYCQVRDNNENEWVFGGGTKLTVLEVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARYIDFGDHMDFWGQGTLVTVSSL
IVLTQPPSVSGAPGQRVTISCSGSSSNIGSNYVSWYQQLPGTAPKLLIYDNNQRPSGVPDRFSGSKSGTSASLAITGLQSEDEADYYCQVRDNNENEWVFGGGTKLTVLEVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARYIDFGDHMDFWGQGTLVTVSSLE

9a6424c4-4096-d62d-4150-e38ebec3799b_HUMAN_32-189_3UX9-A:
Traceback (most recent call last):
  File "/usr/src/app/hommod_rest/services/model.py", line 944, in modelProc
    main_target_sequence, main_domain_range)
  File "/usr/src/app/hommod_rest/services/model.py", line 628, in _build_for_domain
    targetsInterproRanges, picker)
  File "/usr/src/app/hommod_rest/services/domainalign.py", line 439, in pickAlignments
    if picker.accepts(targetID, alignment):
  File "/usr/src/app/hommod_rest/services/interaction.py", line 80, in accepts
    sstart, send = get_target_covered_range(subjectChainAlignment, sseq)
  File "/usr/src/app/hommod_rest/services/modelutils.py", line 812, in get_target_covered_range
    % (alignment['template'], template_seq))
Exception: mismatch between alignment and template sequence:
IVLTQPPSVSGAPGQRVTISCSGSSSNIGSNYVSWYQQLPGTAPKLLIYDNNQRPSGVPDRFSGSKSGTSASLAITGLQSEDEADYYCQVRDNNENEWVFGGGTKLTVLEVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARYIDFGDHMDFWGQGTLVTVSSL
IVLTQPPSVSGAPGQRVTISCSGSSSNIGSNYVSWYQQLPGTAPKLLIYDNNQRPSGVPDRFSGSKSGTSASLAITGLQSEDEADYYCQVRDNNENEWVFGGGTKLTVLEVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARYIDFGDHMDFWGQGTLVTVSSLE
```

@cbaakman, can you explain what the cause is before fixing it?

**Comment by cbaakman** [comment]
The problem is that there are multiple versions of the template sequence and hommod has used the wrong one.
Template sequence as in pdb file:
```
IVLTQPPSVSGAPGQRVTISCSGSSSNIGSNYVSWYQQLPGTAPKLLIYDNNQRPSGVPDRFSGSKSGTSASLAITGLQSEDEADYYCQVRDNNENEWVFGGGTKLTVLEVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARYIDFGDHMDFWGQGTLVTVSSL
```
Template sequence after yasara symmetry build: (notice extra E)
```
IVLTQPPSVSGAPGQRVTISCSGSSSNIGSNYVSWYQQLPGTAPKLLIYDNNQRPSGVPDRFSGSKSGTSASLAITGLQSEDEADYYCQVRDNNENEWVFGGGTKLTVLEVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARYIDFGDHMDFWGQGTLVTVSSLE
```

In order to fix this I will make sure the yasara version of the sequence will be sent through, not the pdb version.

**Comment by jonblack** [comment]
Why are there multiple versions of the template sequence? How does hommod decide which one to use?

**Comment by cbaakman** [comment]
There are multiple versions because yasara can fix up a template, add residues to it because of symmetry. These added residues will also become part of the sequence.

Theoretically, hommod should always use the sequence of the template as in yasara, right before it starts modelling. But in this case I made a mistake by using the dssp files as a data source instead. I shouldn't have done that.
