### ISSUE TITLE
HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-api#70]
```
Message type: ERROR
Location: /usr/src/app/hope/services/hommod.py:68
Module: hommod
Function: run
Time: 2017-03-28 10:03:59,680
Message:
Model job failed:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 60, in create_model
    template_id)
  File "/usr/src/app/hommod_rest/services/model.py", line 786, in modelProc
    ranges = interpro.get_domain_locations(main_target_sequence)
  File "/usr/src/app/hommod_rest/services/interpro.py", line 198, in get_domain_locations
    filepath = self._create_data_file(sequence)
  File "/usr/src/app/hommod_rest/services/interpro.py", line 172, in _create_data_file
    status = _interpro_get_status(jobid)
  File "/usr/src/app/hommod_rest/services/interpro.py", line 83, in _interpro_get_status
    return _interpro_get(_interpro_base_url + '/status/' + jobid)
  File "/usr/src/app/hommod_rest/services/interpro.py", line 63, in _interpro_get
    reqH = urllib2.urlopen(req)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by cbaakman** [comment]
The server at  http://www.ebi.ac.uk/Tools/services/rest/iprscan5/status/<jobid> seems to have returned a 500. It doesn't do it now though, could have been an incident.

**Comment by jonblack** [comment]
Hommod should handle that error in some way. Is there anything it can do?

**Comment by cbaakman** [comment]
We could make hommod resend the request whenever the response code is 500. Is that OK to you?

**Comment by jonblack** [comment]
If it's sent every ten seconds anyway, I'd just ignore the failure. Will the job eventually timeout?

**Comment by cbaakman** [comment]
If the status does not return 'finished' and the response code 500 is ignored, then the job will eventually timeout.
